name: 'Take Webpage Screenshot'
author: 'Karol Brejna'
description: 'Take a screenshot of a webpage or its element'
branding:
    icon: 'layout'
    color: 'blue'
inputs:
  url: 
    description: 'The URL of the page to be captured'
    required: true
  mode:
    description: |
      Mode of operation. Possible values:
      * page
      * wholePage
      * scrollToElement
      * element - capture a specific element by selector (see: "selector" and "xpath" input)
      * script
    default: wholePage
  selector:
    description: |
      CSS selector of the element to be captured or element to which the view should be scrolled. 
      Can be used in "element" and "scrollToElement" modes.
      Use "selector" or "xpath" input, not both.
    required: false
  xpath:
    description: |
      xpath expression for the element to be captured or element to which the view should be scrolled. 
      Can be used in "element" and "scrollToElement" modes.
      Use "selector" or "xpath" input, not both.
    required: false
  scriptBefore:
    description: |
      Script to be executed before the screenshot is taken. 
      Can be used in "script", "page", "wholePage" mode.
    required: false

outputs:
  time: # output will be available to future steps
    description: 'The current time after waiting'
runs:
  using: 'node16'
  main: 'dist/index.js'
